development:
  adapter: async
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"] %>
  channel_prefix: Sororitree_production
