meta_product_name: "Sororitree"
meta_title: "Sororitree - Conectando mulheres"
meta_description: "Com o objetivo de criar um rede de sororidade, essa plataforma é um ambiente seguro para mulheres compartilharem experiências e conversarem sobre os mais diversos tópicos em especial os considerados tabus pela sociedade!"
meta_image: "banner_home_meta.jpg"
twitter_account: "@lewagonbrasil"
